attendance/urls.py
from django.urls import path

from . import views

app_name = "attendance"

urlpatterns = [
    path("", views.Attendance.as_view(), name="index"),
]

community_board_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path("", views.main, name="main"),
    path("", include("user_auth.urls")),
    path("attendance", include("attendance.urls")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

user_auth/urls.py
from django.urls import path

from . import views

app_name = "user_auth"
urlpatterns = [
    path("login", views.Login.as_view(), name="login"),
    path("logout", views.Logout.as_view(), name="logout"),
    path("signup", views.SignUp.as_view(), name="signup"),
    path("changepassword", views.ChangePassword.as_view(), name="changepassword"),
]

attendance/models.py
from django.db import models

# Create your models here.
class AttendanceManager(models.Manager):
    def add(self, name: str, context: str):
        model = self.model(name=name, context=context)
        model.save()
        return model
    
    def get(self, name: str):
        return super().get(name=name)
    
    def create(self, name: str, context: str):
        return super().create(name=name, context=context)
    
class AttendanceModel(models.Model):
    name = models.CharField(max_length=50)   # 'name' 필드, 최대 길이 100자
    context = models.CharField(max_length=500) # 'context' 필드, 최대 길이 500자
    
    objects = AttendanceManager()

    def __str__(self):
        return f"({self.name}, {self.context})"

    class Meta:
        verbose_name = "출석"
        verbose_name_plural = "출석(들)"

user_auth/models.py
from typing import Any
from django.db import models
from django.contrib.auth.models import AbstractUser, UserManager
from django.core import exceptions

# Create your models here.
class AccountManager(UserManager):
    """
    사용자 정보를 관리하기 위한 기능을 커스텀 하기 위해 분리해 둠
    """
    def create_user(self, username: str, email: str | None = ..., password: list | None = ..., **extra_fields: Any) -> Any:
        try:
            password = self._validate_password(password)
        except:
            return None
        else:
            return super().create_user(username, email, password, **extra_fields)
    
    def _validate_password(self, password: list):
        if len(password) != 2:
            raise exceptions.FieldError("회원 가입에 사용 할 패스워드는 리스트에 담아주세요.: [password, check_password]")
        
        if password[0] != password[1]:
            raise exceptions.ValidationError("두 패스워드가 일치하지 않습니다.")
        
        return password[0]

class Account(AbstractUser):
    """
    사용자 정보를 Django에서 제공하는 정보로 사용하지만 나중에 커스텀 할 수 있도록 분리해 둠
    """
    objects = AccountManager()

attendance/forms.py
from django import forms
from .models import AttendanceModel

class AttendanceModelForm(forms.ModelForm):
    class Meta:
        model = AttendanceModel
        fields = ['name', 'context']
        widgets = {
            'context': forms.Textarea(attrs={'rows': 4, 'cols': 40}),  # rows와 cols는 원하는 크기에 맞게 조정
        }

attendance/views.py
from django.shortcuts import render, redirect
from django.http import HttpRequest, HttpResponse
from django.views import View
from .models import AttendanceModel

# Create your views here.
class Attendance(View):

    def get(self, request: HttpRequest) -> HttpResponse:
        data = AttendanceModel.objects.all()
        
        context = {
            "data": data
        }
        
        return render(request, "attendance/index.html", context=context)
    
    def post(self, request: HttpRequest) -> HttpResponse:
        name = request.POST.get("name")
        context = request.POST.get("context")
        
        AttendanceModel.objects.create(name, context)
        
        return redirect("attendance:index")

community_board_project/views.py
from django.shortcuts import render

def main(request):
    return render(request, "index.html")

user_auth/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.http import HttpRequest
from django.contrib import auth

from .models import Account

class Login(View):
    """
    로그인을 위한 기능이 구현되어 있습니다.
    """
    def get(self, request: HttpRequest):
        """
        로그인 요청에 대해 관련 페이지를 제공합니다.
        """
        user = request.user
        
        if user.is_authenticated:
            return render(request, "user_auth/already_logined.html")
        
        return render(request, "user_auth/login.html")
    
    def post(self, request: HttpRequest):
        """
        로그인 요청에 대해 이메일 주소와 패스워드를 확인하여 거부/승낙 처리를 합니다.
        """
        email = request.POST.get("email")
        password = request.POST.get("password")
        
        user = auth.authenticate(username=email, password=password)
        
        if user.is_authenticated:
            auth.login(request, user)
            return redirect("/")
        
        context = {
            "data": request.POST,
            "valid": "is-invalid",
            "message": "로그인 실패! 이메일 주소와 패스워드를 다시 확인하세요.",
        }
        
        return render(request, "user_auth/login.html", context=context)
    
class Logout(View):
    """
    로그아웃을 위한 기능이 구현되어 있습니다.
    """
    def get(self, request: HttpRequest):
        """
        로그아웃 요청에 대해 로그아웃 처리합니다.
        """
        user = request.user
        
        if user.is_authenticated:
            auth.logout(request)
            return redirect("/")
    
class SignUp(View):
    """
    회원 가입을 위한 기능이 구현되어 있습니다.
    """
    def get(self, request: HttpRequest):
        """
        회원 가입 요청에 대해 관련 페이지를 제공합니다.
        """
        user = request.user
        
        if user.is_authenticated:
            return render(request, "user_auth/already_logined.html")
        
        return render(request, "user_auth/signup.html")
    
    def post(self, request: HttpRequest):
        """
        회원 가입 요청에 대해 이메일 주소와 패스워드 등의 정보를 검증 후 거부/승낙 처리를 합니다.
        """
        email = request.POST.get("email")
        password = request.POST.getlist("password")
        first_name = request.POST.get("first_name")
        last_name = request.POST.get("last_name")
        
        user = Account.objects.create_user(username=email, email=email, password=password, first_name=first_name, last_name=last_name)
        
        if not user:
            context = {
                "data": request.POST,
                "valid": "is-invalid",
                "message": "회원 가입 실패! 이메일 주소와 패스워드를 다시 확인하세요.",
            }
            return render(request, "user_auth/signup.html", context=context)
        
        return redirect("/")
            
    
class ChangePassword(View):
    def get(self, request: HttpRequest):
        pass
    
    def post(self, request: HttpRequest):
        pass
    
    

attendance/templates/attendance/index.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DB 저장 테스트</title>
    {% include "modules/bootstrap.html" %}
</head>
<body>
    {% include "modules/header.html" %}
    <section class="container px-4 py-5">
        <h2 class="pb-2 border-bottom">DB 저장 테스트</h2>
        <form class="" action="{% url 'attendance:index' %}" method="POST">
        {% csrf_token %}
            <div class="row g-2">
                <div class="col-sm col-md-4">
                    <div class="form-floating">
                        <input type="text" class="form-control" id="id_name" name="name" placeholder="이름">
                        <label for="id_name">이름</label>
                    </div>
                </div>
                <div class="col-sm col-md-8">
                    <div class="form-floating">
                        <textarea class="form-control" id="id_context" name="context" placeholder="내용"></textarea>
                        <label for="id_context">내용</label>
                    </div>
                </div>
                <div class="col-sm col-md">
                    <div class="d-grid">
                        <button class="btn btn-primary" type="submit">저장</button>
                    </div>
                </div>
            </div>
        </form>
        <div class="container-fluid mt-3">
            <table class="table table-striped">
                <tbody>
                    {% for d in data %}
                        <tr class="row">
                            <td class="align-top col-sm col-md-4">
                                {{ d.name }}
                            </td>
                            <td class="col-sm col-md-8">
                                {{ d.context|linebreaks }}
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </section>
</body>
<script type="text/javascript">
const textarea = document.getElementById("id_context")

// 글자의 크기를 측정하여 요소의 높이로 사용하는 것에 오차가 존재하기 때문에 개행이 많아질수록 공간이 크게 남는다.
textarea.addEventListener("input", function() {
    const lines = this.value.split("\n").length
    const line_height = parseFloat(window.getComputedStyle(this).fontSize) * 1.5
    this.style.height = `${line_height * lines + line_height - (lines * 2)}px` // 여기서 어떻게는 오차를 줄이기 위한 작업을 했지만 소용 없어...
})
</script>
</html>

templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    {% include "modules/bootstrap.html" %}
</head>
<body>
    {% include "modules/header.html" %}
    <div class="container mt-4">
        <div class="row">
            <div class="col-md-4">
                <div class="card">
                    <img src="{% static 'bs5/image/image1.png' %}" class="card-img-top" alt="Image 1">
                    <div class="card-body">
                        <h5 class="card-title">파커 1</h5>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card">
                    <img src="{% static 'bs5/image/image2.png' %}" class="card-img-top" alt="Image 2">
                    <div class="card-body">
                        <h5 class="card-title">파커 2</h5>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card">
                    <img src="{% static 'bs5/image/image3.png' %}" class="card-img-top" alt="Image 3">
                    <div class="card-body">
                        <h5 class="card-title">파커 3</h5>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
</body>
</html>

templates/modules/bootstrap.html
{% load static %}
<link rel="stylesheet" href="{% static 'bs5/css/bootstrap.min.css' %}" />
<script type="text/javascript" src="{% static 'bs5/js/bootstrap.bundle.min.js' %}"></script>

templates/modules/custom_style.html
<style>
    .bi {
        fill: currentColor;
    }
</style>

templates/modules/header.html
<svg xmlns="http://www.w3.org/2000/svg" class="d-none">
    <symbol id="bootstrap" viewBox="0 0 118 94">
        <title>Bootstrap</title>
        <path fill-rule="evenodd" clip-rule="evenodd" d="M24.509 0c-6.733 0-11.715 5.893-11.492 12.284.214 6.14-.064 14.092-2.066 20.577C8.943 39.365 5.547 43.485 0 44.014v5.972c5.547.529 8.943 4.649 10.951 11.153 2.002 6.485 2.28 14.437 2.066 20.577C12.794 88.106 17.776 94 24.51 94H93.5c6.733 0 11.714-5.893 11.491-12.284-.214-6.14.064-14.092 2.066-20.577 2.009-6.504 5.396-10.624 10.943-11.153v-5.972c-5.547-.529-8.934-4.649-10.943-11.153-2.002-6.484-2.28-14.437-2.066-20.577C105.214 5.894 100.233 0 93.5 0H24.508zM80 57.863C80 66.663 73.436 72 62.543 72H44a2 2 0 01-2-2V24a2 2 0 012-2h18.437c9.083 0 15.044 4.92 15.044 12.474 0 5.302-4.01 10.049-9.119 10.88v.277C75.317 46.394 80 51.21 80 57.863zM60.521 28.34H49.948v14.934h8.905c6.884 0 10.68-2.772 10.68-7.727 0-4.643-3.264-7.207-9.012-7.207zM49.948 49.2v16.458H60.91c7.167 0 10.964-2.876 10.964-8.281 0-5.406-3.903-8.178-11.425-8.178H49.948z"></path>
    </symbol>
</svg>
<header class="p-3 text-bg-success">
    <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
            <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
                <svg style="fill: currentColor;" class="me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"></use></svg>
            </a>

            <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                <li><a href="{% url 'main' %}" class="nav-link px-2 text-white">Home</a></li>
                <li><a href="{% url 'attendance:index' %}" class="nav-link px-2 text-white">상품</a></li>
                <li><a href="#" class="nav-link px-2 text-white">테스트1</a></li>
                <li><a href="#" class="nav-link px-2 text-white">테스트2</a></li>
                <li><a href="#" class="nav-link px-2 text-white">테스트3</a></li>
            </ul>

            <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" role="search">
                <input type="search" class="form-control form-control-white text-bg-success text-white" placeholder="Search..." aria-label="Search">
            </form>

            {% if user.is_authenticated %}
                <div class="text-end">
                    <button type="button" class="btn btn-outline-light me-2" onclick="window.location.href='{% url 'user_auth:logout' %}'">Logout</button>
                    <button type="button" class="btn btn-warning" onclick="window.location.href='{% url 'user_auth:signup' %}'">{{ user.username }}</button>
                </div>
            {% else %}
                <div class="text-end">
                    <button type="button" class="btn btn-outline-light me-2" onclick="window.location.href='{% url 'user_auth:login' %}'">Login</button>
                    <button type="button" class="btn btn-warning" onclick="window.location.href='{% url 'user_auth:signup' %}'">Sign-up</button>
                </div>
            {% endif %}
        </div>
    </div>
</header>

user_auth/templates/user_auth/already_logined.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Message</title>
    {% include "modules/bootstrap.html" %}
</head>
{% include "modules/custom_style.html" %}
<body>
    <div class="modal modal-sheet d-block bg-body-secondary p-4 py-md-5" tabindex="-1" role="dialog" id="modalChoice">
        <div class="modal-dialog" role="document">
            <div class="modal-content rounded-3 shadow">
            <div class="modal-body p-4 text-center">
                <h5 class="mb-0">이미 로그인 되어 있습니다.</h5>
                <p class="mb-0">로그아웃을 하시겠습니까?</p>
            </div>
            <div class="modal-footer flex-nowrap p-0">
                <button type="button" class="btn btn-lg btn-link fs-6 text-decoration-none col-6 py-3 m-0 rounded-0 border-end" onclick="window.location.href='{% url 'user_auth:logout' %}'"><strong>예</strong></button>
                <button type="button" class="btn btn-lg btn-link fs-6 text-decoration-none col-6 py-3 m-0 rounded-0" onclick="history.back()">아니오</button>
            </div>
            </div>
        </div>
    </div>
</body>
</html>

user_auth/templates/user_auth/login.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>로그인</title>
    {% include "modules/bootstrap.html" %}
</head>
{% include "modules/custom_style.html" %}
<body>
    <svg xmlns="http://www.w3.org/2000/svg" class="d-none">
        <symbol id="github" viewBox="0 0 16 16">
            <path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.012 8.012 0 0 0 16 8c0-4.42-3.58-8-8-8z"></path>
        </symbol>

        <symbol id="twitter" viewBox="0 0 16 16">
            <path d="M5.026 15c6.038 0 9.341-5.003 9.341-9.334 0-.14 0-.282-.006-.422A6.685 6.685 0 0 0 16 3.542a6.658 6.658 0 0 1-1.889.518 3.301 3.301 0 0 0 1.447-1.817 6.533 6.533 0 0 1-2.087.793A3.286 3.286 0 0 0 7.875 6.03a9.325 9.325 0 0 1-6.767-3.429 3.289 3.289 0 0 0 1.018 4.382A3.323 3.323 0 0 1 .64 6.575v.045a3.288 3.288 0 0 0 2.632 3.218 3.203 3.203 0 0 1-.865.115 3.23 3.23 0 0 1-.614-.057 3.283 3.283 0 0 0 3.067 2.277A6.588 6.588 0 0 1 .78 13.58a6.32 6.32 0 0 1-.78-.045A9.344 9.344 0 0 0 5.026 15z"></path>
        </symbol>

        <symbol id="facebook" viewBox="0 0 16 16">
            <path d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951z"></path>
        </symbol>
    </svg>
    <div class="modal modal-sheet d-block bg-body-secondary p-4 py-md-5" tabindex="-1" role="dialog" id="modalSignin">
        <div class="modal-dialog" role="document">
            <div class="modal-content rounded-4 shadow">
            <div class="modal-header p-5 pb-4 border-bottom-0">
                <h1 class="fw-bold mb-0 fs-2">로그인</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close" onclick="window.location.href='{% url 'main' %}'"></button>
            </div>

            <div class="modal-body p-5 pt-0">
                <form class="" action="{% url 'user_auth:login' %}" method="POST">
                    {% csrf_token %}
                    <div class="form-floating mb-3">
                        <input type="email" class="form-control rounded-3 {{ valid }}" id="floatingInput" name="email" value="{{ data.email }}" placeholder="email@domain.com">
                        <label for="floatingInput">이메일</label>
                    </div>
                    <div class="form-floating mb-3">
                        <input type="password" class="form-control rounded-3 {{ valid }}" id="floatingPassword" name="password" placeholder="Password">
                        <label for="floatingPassword">패스워드</label>
                        {% if message %}
                            <div class="invalid-feedback">
                                {{ message }}
                            </div>
                        {% endif %}
                    </div>
                    <button class="w-100 mb-2 btn btn-lg rounded-3 btn-primary" type="submit">로그인</button>
                    <small class="text-body-secondary">계정이 없으신가요? <a href="{% url 'user_auth:signup' %}">여기</a>에서 가입을 하세요.</small>
                    <hr class="my-4">
                    <button class="w-100 py-2 mb-2 btn btn-outline-secondary rounded-3" type="submit">
                        <svg class="bi me-1" width="16" height="16"><use xlink:href="#twitter"></use></svg>
                        Twitter로 로그인 하기
                    </button>
                    <button class="w-100 py-2 mb-2 btn btn-outline-secondary rounded-3" type="submit">
                        <svg class="bi me-1" width="16" height="16"><use xlink:href="#facebook"></use></svg>
                        Facebook으로 로그인 하기
                    </button>
                    <button class="w-100 py-2 mb-2 btn btn-outline-primary rounded-3" type="submit">
                        <svg class="bi me-1" width="16" height="16"><use xlink:href="#github"></use></svg>
                        GitHub로 로그인 하기
                    </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

user_auth/templates/user_auth/signup.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sign up</title>
    {% include "modules/bootstrap.html" %}
</head>
{% include "modules/custom_style.html" %}
<body>
    <div class="modal modal-sheet d-block bg-body-secondary p-4 py-md-5" tabindex="-1" role="dialog" id="modalSignin">
        <div class="modal-dialog" role="document">
            <div class="modal-content rounded-4 shadow">
            <div class="modal-header p-5 pb-4 border-bottom-0">
                <h1 class="fw-bold mb-0 fs-2">Sign up</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close" onclick="window.location.href='{% url 'main' %}'"></button>
            </div>

            <div class="modal-body p-5 pt-0">
                <form class="" action="{% url 'user_auth:signup' %}" method="POST">
                    {% csrf_token %}
                    <div class="form-floating mb-3">
                        <input type="email" class="form-control rounded-3 {{ valid }}" id="id_email" name="email" value="{{ data.email }}" placeholder="email@domain.com">
                        <label for="id_email">이메일</label>
                    </div>
                    <div class="form-floating mb-3">
                        <input type="password" class="form-control rounded-3 {{ valid }}" id="id_password1" name="password" placeholder="패스워드">
                        <label for="id_password1">패스워드</label>
                    </div>
                    <div class="form-floating mb-3">
                        <input type="password" class="form-control rounded-3 {{ valid }}" id="id_password2" name="password" placeholder="패스워드 확인">
                        <label for="id_password2">패스워드 확인</label>
                    </div>
                    <div class="form-floating mb-3">
                        <input type="text" class="form-control rounded-3 {{ valid }}" id="id_last_name" name="last_name" value="{{ data.last_name }}" placeholder="성">
                        <label for="id_last_name">성</label>
                    </div>
                    <div class="form-floating mb-3">
                        <input type="text" class="form-control rounded-3 {{ valid }}" id="id_first_name" name="first_name" value="{{ data.first_name }}" placeholder="이름">
                        <label for="id_first_name">이름</label>
                    </div>
                    <button class="w-100 mb-2 btn btn-lg rounded-3 btn-primary" type="submit">가입</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</body>
</html>